services:
  qdrant:
    image: qdrant/qdrant:latest
    networks:
      - rag_net
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
  mongodb:
    image: mongo:latest
    networks:
      - rag_net
    ports:
      - "27017:27017" # MongoDB Port
    volumes:
      - mongodb_data:/data/db

volumes:
  qdrant_data:
  mongodb_data:

networks:
  rag_net:
    name: rag-pipeline-net
    driver: bridge
